# Generated by Django 4.0.4 on 2022-05-02 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftVehicles',
            fields=[
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateField(auto_now_add=True)),
                ('bill', models.FloatField(default=0.0)),
                ('transaction_id', models.CharField(default='<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.DateTimeField>_<django.db.models.fields.DateField>', max_length=200, primary_key=True, serialize=False)),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.account')),
            ],
        ),
    ]
