# Generated by Django 4.0.4 on 2022-05-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftvehicles',
            name='time_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leftvehicles',
            name='time_out',
            field=models.DateField(),
        ),
    ]
