# Generated by Django 4.0.4 on 2022-05-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkedVehicles',
            fields=[
                ('time_in', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('time_out', models.DateField(auto_now_add=True)),
                ('bill', models.FloatField(default=0.0)),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.account')),
            ],
        ),
    ]
