# Generated by Django 4.0.4 on 2022-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('available_slots', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
