# Generated by Django 4.0.4 on 2022-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('mobile_number', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
